kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name | quote }}
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
spec:
  host: {{ .Values.application_domain | quote }}
  to:
    kind: Service
    name: {{ .Values.name | quote }}
